---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: ops
  namespace: default
  labels:
    app: ops-tools
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: ops-tools
    spec:
      containers:
      - name: server
        image: rmoreira/ops-tools:latest
        imagePullPolicy: Always
        command: ["/bin/bash", "-ec", "while :; do echo '.'; sleep 3600 ; done"]
      restartPolicy: Always
